# Generated by Django 4.2.13 on 2024-06-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.TextField()),
                ('department_created_on', models.DateTimeField(auto_now_add=True)),
                ('department_updated_on', models.DateTimeField(auto_now=True)),
                ('department_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_created_by', to=settings.AUTH_USER_MODEL)),
                ('department_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
