# Generated by Django 4.2.13 on 2024-06-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_template_name', models.CharField(max_length=100)),
                ('checklist_template_description', models.TextField()),
                ('checklist_template_created_on', models.DateTimeField(auto_now_add=True)),
                ('checklist_template_updated_on', models.DateTimeField(auto_now=True)),
                ('checklist_template_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_description', models.TextField()),
                ('team_created_on', models.DateTimeField(auto_now_add=True)),
                ('team_updated_on', models.DateTimeField(auto_now=True)),
                ('team_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
                ('team_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_department', to='checklist.department')),
                ('team_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_template_name', models.CharField(max_length=100)),
                ('task_template_description', models.TextField()),
                ('task_template_due_at', models.DateTimeField()),
                ('task_template_created_on', models.DateTimeField(auto_now_add=True)),
                ('task_template_updated_on', models.DateTimeField(auto_now=True)),
                ('task_template_checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_template_checklist_template', to='checklist.checklisttemplate')),
                ('task_template_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_template_created_by', to=settings.AUTH_USER_MODEL)),
                ('task_template_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_template_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='checklist_template_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template_team', to='checklist.team'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='checklist_template_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
