# Generated by Django 4.2.13 on 2024-06-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0003_alter_tasktemplate_task_template_due_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_instance_processed_on', models.DateTimeField(auto_now=True)),
                ('task_instance_processor_notes', models.TextField()),
                ('task_instance_verified_on', models.DateTimeField(auto_now=True)),
                ('task_instance_verifier_notes', models.TextField()),
                ('task_instance_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Awaiting Verification', 'Awaiting Verification'), ('Completed', 'Completed')], default='Not Started', max_length=100)),
                ('task_instance_processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_processed_by', to=settings.AUTH_USER_MODEL)),
                ('task_instance_task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_task_template', to='checklist.tasktemplate')),
                ('task_instance_verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Instance',
                'verbose_name_plural': 'Task Instances',
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_instance_created_on', models.DateTimeField(auto_now_add=True)),
                ('checklist_instance_checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instance_checklist_template', to='checklist.checklisttemplate')),
                ('checklist_instance_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instance_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Instance',
                'verbose_name_plural': 'Checklist Instances',
            },
        ),
    ]
