# Generated by Django 4.2.13 on 2024-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_rename_checklist_instance_checklist_template_checklistinstance_checklist_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
