# Generated by Django 4.2.13 on 2024-06-27 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_team_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
