# Generated by Django 4.2.13 on 2024-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_team_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
