# Generated by Django 4.2.13 on 2024-06-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0008_alter_team_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='processed_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='processor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='verified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='verifier_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
