# Generated by Django 4.2.13 on 2024-06-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_alter_checklisttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='checklist_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instance_checklist_instance', to='checklist.checklistinstance'),
        ),
    ]
