# Generated by Django 4.2.13 on 2024-06-28 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
