# Generated by Django 4.2.13 on 2024-06-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_taskinstance_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
