# Generated by Django 4.2.13 on 2024-06-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_alter_taskinstance_processed_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='processor_notes',
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='verifier_notes',
        ),
    ]
